#url相关配置，这里配置url的基本url
server:
  port: 8080
spring:
  ## Elasticsearch配置文件（必须）
  ## 该配置和Elasticsearch本地文件config下的elasticsearch.yml中的配置信息有关
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300
  #thymeleaf
  thymeleaf:
    encoding: UTF-8
    # 热部署静态文件
    cache: false
    # 使用HTML5标准
    mode: HTML5
  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #这里加上后缀用来防止mysql乱码,serverTimezone=GMT%2b8设置时区
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf-8&useSSL=false
    username: root
    password: qcl123
  #jpa相关
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #返回的api接口的配置，全局有效
  jackson:
    default-property-inclusion: non_null #如果某一个字段为null，就不再返回这个字段
